spring.application.name=SpringBootWeb
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/personalwork/Documents/SpringBoot-h2-db/employee
spring.datasource.username=chandanDB
spring.datasource.password=test@123
spring.jpa.hibernate.ddl-auto=update